# Generated by Django 3.2.16 on 2022-12-11 05:38

import django.contrib.postgres.fields
from django.db import migrations, models

import postgres_composite_types.fields
import postgres_composite_types.operations
import tests.fields
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        postgres_composite_types.operations.CreateType(
            name="Point",
            fields=[
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
            options={
                "db_table": "test_point",
            },
        ),
        postgres_composite_types.operations.CreateType(
            name="Box",
            fields=[
                ("top_left", tests.models.Point.Field()),
                ("bottom_right", tests.models.Point.Field()),
            ],
            options={
                "db_table": "test_box",
            },
        ),
        postgres_composite_types.operations.CreateType(
            name="Card",
            fields=[
                ("suit", models.CharField(max_length=1)),
                ("rank", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "card",
            },
        ),
        postgres_composite_types.operations.CreateType(
            name="DateRange",
            fields=[
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
            options={
                "db_table": "test_date_range",
            },
        ),
        postgres_composite_types.operations.CreateType(
            name="DescriptorType",
            fields=[
                ("value", tests.fields.TriplingIntegerField()),
            ],
            options={
                "db_table": "test_custom_descriptor",
            },
        ),
        migrations.CreateModel(
            name="DescriptorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    tests.models.DescriptorType.Field(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cards",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=tests.models.Card.Field(),
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("bounding_box", tests.models.Box.Field()),
            ],
        ),
        migrations.CreateModel(
            name="NamedDateRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "date_range",
                    tests.models.DateRange.Field(),
                ),
            ],
        ),
        postgres_composite_types.operations.CreateType(
            name="OptionalBits",
            fields=[
                ("required", models.CharField(max_length=32)),
                ("optional", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "optional_type",
            },
        ),
        migrations.CreateModel(
            name="OptionalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "optional_field",
                    tests.models.OptionalBits.Field(blank=True, null=True),
                ),
            ],
        ),
        postgres_composite_types.operations.CreateType(
            name="SimpleType",
            fields=[
                ("a", models.IntegerField(verbose_name="A number")),
                ("b", models.CharField(max_length=32, verbose_name="A name")),
                ("c", models.DateTimeField(verbose_name="A date")),
            ],
            options={
                "db_table": "test_type",
            },
        ),
        migrations.CreateModel(
            name="SimpleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_field",
                    tests.models.SimpleType.Field(),
                ),
            ],
        ),
    ]
