# Generated by Django 2.0.2 on 2018-03-04 23:12

import django.contrib.postgres.fields
from django.db import migrations, models

import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', tests.models.DescriptorTypeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', django.contrib.postgres.fields.ArrayField(base_field=tests.models.CardField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bounding_box', tests.models.BoxField()),
            ],
        ),
        migrations.CreateModel(
            name='NamedDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_range', tests.models.DateRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='OptionalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional_field', tests.models.OptionalBitsField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', tests.models.SimpleTypeField()),
            ],
        ),
    ]
